name: DMND Deploy
on:
  # See: https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  push:
    branches:
      - "feat/353--oci-image-cicd"
    tags:
      - "*"

jobs:
  deploy-oci-image:
    name: Deploy OCI image
    runs-on: ubuntu-24.04
    steps:
      - id: sanitize
        run: |
          IMAGE_TAG="$(echo "${GITHUB_REF_NAME}" | sed 's/\//-/g')"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: deployment/package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Node.js dependencies for frontend
        run: npm ci --legacy-peer-deps
        working-directory: deployment
      - name: Install Node.js dependencies for Pulumi project
        run: npm install
        working-directory: deployment
      - uses: pulumi/actions@v6
        with:
          command: up
          config-map: |
            sv2-tp:imageTag:
              value: ${{ steps.sanitize.outputs.image_tag }}
          # stack-name: dmnd-tech-org/sv2-tp/production
          stack-name: ${{ secrets.PULUMI_ORGANIZATION }}/sv2-tp/production
          work-dir: deployment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
